on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t pikai/node-server-money-tracker .
      - name: Push Docker Image
        run: docker push pikai/node-server-money-tracker:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull pikai/node-server-money-tracker:latest
      - name: Find available port
        id: find_port
        run: |
          for ((port=8000; port<=8100; port++)); do
            sudo nc -z localhost $port || { echo $port > port.txt; break; }
          done
      - name: Read port from file
        id: read_port
        run: echo "::set-output name=port_number::$(cat port.txt)"
      - name: Run Container
        run: docker run -d -p ${{ steps.read_port.outputs.port_number }}:8001 --rm --name server-contain -e MONGO_URL='${{ secrets.MONGO_URL }}' pikai/node-server-money-tracker
